version: "3.9"

services:
  client:
    build:
      context: ./client
    ports:
      - "5173:5173"
    restart: always
    container_name: client 
    volumes:
      - ./client:/app/src
    stdin_open: true
    tty: true
    networks:
      - mynet

  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: always
    ports:
      - '3003:3000'
    volumes:
      - ./grafana:/var/lib/grafana
      - ./grafana/config/grafana.ini:/etc/grafana/grafana.ini 
    networks:
      - mynet

  db:
    image: timescale/timescaledb:latest-pg14
    restart: always
    container_name: timescaledb 
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      -  ./data:/var/lib/postgresql/data
    networks:
      - mynet

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - mynet
  
  server:
    build:
      context: ./server
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - ./server:/server
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
    depends_on:
      - db
    networks:
      - mynet
  

volumes:
  db_data:
    driver: local

networks:
  mynet:
    driver: bridge
